name: "FAP: Build"

on:
  push:
    tags:
      - 'v*.*.*' 
  pull_request:
  schedule:
    - cron: "1 1 * * *"

jobs:
  ufbt-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # FAP Channels; see ufbt action docs for more info
          - name: dev channel
            sdk-channel: dev
          - name: release channel
            sdk-channel: release

    name: 'ufbt: Build for ${{ matrix.name }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with ufbt
        id: build-app
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          sdk-channel: ${{ matrix.sdk-channel }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
