name: "FAP: Build and Release for multiple SDK sources"

on:
  push:
    tags:
      - 'v*.*.*' 
  pull_request:
    - cron: "1 1 * * *"

jobs:
  ufbt-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # FAP Channels; see ufbt action docs for more info
          - name: dev channel
            sdk-channel: dev
          - name: release channel
            sdk-channel: release

    name: 'ufbt: Build for ${{ matrix.name }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with ufbt
        id: build-app
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          sdk-channel: ${{ matrix.sdk-channel }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.build-app.outputs.fap-artifacts }}/${{ github.repository }}-${{ steps.build-app.outputs.suffix }}
